### ISSUE TITLE
Grouping of files within a dataset

### ISSUE THREAD

**Issue by paulmillar** [EGI-Federation/eosc-data-transfer#16]
Some DOIs point to a large number of files.  A user may be interested in only a subset of these files.

When resolving a DOI to a set of files, the catalogue may identify those files into groups.  As a concrete example, at ESRF, some DOIs point to multiple datasets, where each of the datasets has a distinct name and each contains a separate collection of files.

For example, a DOI could resolve to three datasets

    doi:10.15151/ESRF-xxxxxx   -->  {dataset-A, dataset-B, dataset-C}

Each of the datasets could have multiple files:

    dataset-A  --> {ds-a-file-1, ds-a-file-2, ...}
    dataset-B  --> {ds-b-file-1, ds-b-file-2, ...}
    dataset-C  --> {ds-c-file-1, ds-c-file-2, ...}

One possible way of handling this involves each file being associated with zero or more filesets, where a fileset is simply a text label that is used to group together related files.

Given the above example, this would look like:

    ds-a-file-1 filesets ---> {"dataset-A"}
    ds-a-file-2 filesets ---> {"dataset-A"}
    ds-a-file-3 filesets ---> {"dataset-A"}
    [...]
    ds-b-file-1 filesets ---> {"dataset-B"}
    ds-b-file-2 filesets ---> {"dataset-B"}
    ds-b-file-3 filesets ---> {"dataset-B"}
    [ ...]
    ds-c-file-1 filesets ---> {"dataset-C"}
    ds-c-file-2 filesets ---> {"dataset-C"}
    ds-c-file-3 filesets ---> {"dataset-C"}
    [...]

**Comment by thebe14** [comment]
This still does not help with organizing files in a hierarchical structure. For that a path (with a default value of "/") field is needed on the `StorageElement` class.
