### ISSUE TITLE
Create/modified date times of ESRF files incorrect

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/eosc-data-transfer#7]
# Short Description of the issue

When you parse and ESRF DOI (e.g. https://doi.org/10.15151/ESRF-DC-818569841) the returned files have incorrect creation and modified date times.

**Comment by paulmillar** [comment]
The temporary endpoint available at [this location](https://eosc-data-transfer.test.fedcloud.eu/q/swagger-ui/#/Digital%20Object%20Identifier/parse), was tested on 2023-04-21; in particular the `parse` call was exercised with a DOI like `https://doi.org/10.15151/ESRF-DC-818569841`.

The `parse` API call returned JSON contains`createdAt` and `modifiedAt` values.  These two items had values seem to be the current timestamp.

I'm not sure of the exact semantics of these two fields, but the ESRF ICAT+ API resource `/catalogue​/{sessionId}​/dataset​/id​/{datasetId}​/datafile`  provides creation and modification timestamps.  These are the `createTime` and `modTime` fields under the `Datafile` label.

Here is an edited, illustrative example, where many of the irrelevant fields removed for clarity:

```json
[
  {
    "Datafile": {
      "id": 62544758,
      "createTime": "2017-10-25T14:39:20.614+02:00",
      "modTime": "2017-10-25T14:39:20.614+02:00",
       "fileSize": 116714455,
  },
  {
    "Datafile": {
      "id": 62544759,
```

The ICAT+ response also provide some simple provenance information, indicating which system added this information.  I think we can ignore that information for now.

**Comment by thebe14** [comment]
The API v1.1.43 returns the following from the mentioned DOI:

```json
[{
  "kind": "StorageContent",
  "count": 17,
  "elements": [
    {
      "kind": "StorageElement",
      "name": "mesh-ceru_NaBr6_1_1_data_000001.h5",
      "isFolder": false,
      "size": 116714455,
      "createdAt": "2017-10-25T12:39:20",
      "modifiedAt": "2017-10-25T12:39:20",
      "accessUrl": "https://icatplus.esrf.fr/catalogue/167872ba-8d8c-4b97-8dbf-b8eaadd38f54/data/download?datafileIds=62544758"
    },
...
]
```

Can we consider this closed (no longer an issue)?
