### ISSUE TITLE
Swagger as an invalid example DOI

### ISSUE THREAD

**Issue by paulmillar** [EGI-Federation/eosc-data-transfer#9]
# Short Description of the issue

The Swagger documentation includes an example DOI value for the `/parser` resource: `https://doi.org/12.3456/zenodo.12345678`.  This value appears both in the  `doi` parameter's documentation and as an initial value in the parameter's textbox.

The problem is that this DOI is broken.  Attempting to use it yields an error response.  This makes that specific DOI a poor choice for an example DOI.

One might argue that the consecutive digits are meant to convey this is a placeholder DOI; however, the fact that the value is a placeholder (i.e., will not work) is not documented.  Moreover, DOI.org do not provide a range of DOIs that are reserved for documentation purposes.  (I've already raised this with them, but feel free to report this problem ;-)

This problem is compounded by including the name `zenodo` in the DOI, making it seem that the DOI is valid, since Zenodo is a well-known service that provides DOIs and the DOIs generated by the Zenodo service have suffixes that start with `zenodo` , as shown in the (broken) example.

Suggest doing one of two things: either keep a placeholder DOI as the example but make it clearer (e.g,. document that it is a placeholder, remove `zenodo` in suffix), or update the example DOI to use a valid DOI.

**Comment by thebe14** [comment]
Added a valid DOI as the example.
